### PR TITLE
curl 8.21.0 and its dependencies: update, and move curl to cmake

### PR DESCRIPTION
**Pull request by th0ma7**
Updates curl and everything it depends on, and moves curl from autotools to cmake. Split out of #7397 so that PR can rebase onto this one with fewer packages left to deal with.

| package | from | to |
|---|---|---|
| curl | 8.4.0 | 8.21.0 |
| mbedtls | 3.6.3 | 4.2.0 |
| nghttp2 | 1.58.0 | 1.70.0 |
| nghttp3 | 1.0.0 | 1.18.0 |
| ngtcp2 | 1.0.1 | 1.25.0 |
| gsasl | 2.2.0 | 2.2.4 |
| libidn2 | 2.3.4 | 2.3.8 |
| libpsl | 0.21.2 | 0.23.3 |
| openldap | 2.6.4 | 2.6.9 |

## curl: autotools → cmake

Not an option-for-option translation. cmake and autotools have **opposite defaults** on several features:

```
USE_NGHTTP2  USE_LIBIDN2  CURL_USE_LIBPSL  CURL_USE_LIBSSH2   ON  by default
CURL_DISABLE_LDAP  CURL_DISABLE_WEBSOCKETS                    OFF by default
CURL_ZLIB  CURL_ZSTD  CURL_BROTLI                             AUTO
```

A literal translation would have silently enabled six features the autotools build did not have, and `AUTO` would pick up whatever another package left in the staging tree. Each is therefore stated in both directions, never left to the default.

`--with-librtmp` disappears. That is not a cmake gap — curl 8.21 dropped librtmp entirely, autotools included (`grep -c with-librtmp configure` → 0), so the option was already being ignored.

`curl-config` is still generated and installed by the cmake build, so the existing post-install fixup is unchanged.

## What the new versions needed on old toolchains

**curl — eventfd.** glibc gained `EFD_CLOEXEC`/`EFD_NONBLOCK` in 2.9 with the `eventfd2` syscall. glibc 2.8 has the function *and* the header but not the flags, and both build systems only probe the function, so `socketpair.c` failed on ppc853x-5.2:

```
socketpair.c:40: error: 'EFD_CLOEXEC' undeclared
```

Defining the constants ourselves would compile and then fail at runtime — 2.8's wrapper calls the flagless `eventfd` syscall. Instead `HAVE_EVENTFD=OFF` below glibc 2.9 skips the probe, and curl uses the pipe fallback it already implements.

**mbedtls — submodules.** From 3.6 the release needs `framework/` and `tf-psa-crypto/`, which GitHub's auto-generated tag archive never carries; they extracted empty and cmake stopped with *"not found (and does not appear to be a git checkout)"*. Now taken from the release asset, which bundles them.

PLIST drops `libeverest.so` and `libp256m.so`. Not a missing option: 4.x declares those drivers `add_library(... OBJECT ...)`, folds them into `libtfpsacrypto` and installs no separate `.so` — there is no `install(TARGETS)` for them anywhere in the tree.

**nghttp3 and ngtcp2 — `_Generic`.** 1.x builds its min/max helpers on C11 generic selection, which gcc only implements from 4.9. Older compilers report `expected expression before 'long'` — pointing at the first type in the list rather than at `_Generic`. Measured on the Synology toolchains:

```
gcc 4.6.4  no      gcc 4.7.3  no      gcc 4.8.3  no      gcc 4.9.4  yes
```

Hence `MIN_GCC_VERSION = 4.9` on both.

**openldap stays on 2.6.9.** 2.7.0 puts declarations directly after `case` labels, which is C23 (free positioning of labels). No compiler we have accepts it, the gcc 8.5 overlay included — only gcc 11+ does.

## CI

`build.yml` turns DSM 5.2 on temporarily, since ppc853x-5.2 and x86-5.2 are exactly where these updates broke. **That commit reverts before merge.**

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 it seems that this PR broke the build of the postresql package.
_I know you are offline, so I will have an eye on it later_

In the openssl update #7412 postgresql is broken on armv7-7.1 
Than I built it on the current HEAD and ti failed too, so it is not new by openssl update.


```
[220/230] Linking CXX executable bin/cs2cs
FAILED: bin/cs2cs 
: && /github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++ -I/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/include -D__ARM_PCS_VFP=1 -fPIC -O3 -DNDEBUG -L/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/lib -L/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/lib -Wl,--rpath-link,/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/lib -Wl,--rpath,/var/packages/postgresql/target/lib -D__ARM_PCS_VFP=1 src/CMakeFiles/cs2cs.dir/apps/cs2cs.cpp.o src/CMakeFiles/cs2cs.dir/apps/emess.cpp.o src/CMakeFiles/cs2cs.dir/apps/utils.cpp.o -o bin/cs2cs -L/github/workspace/spk/postgresql/work-armv7-7.1/proj-8.2.1/build/lib -Wl,-rpath,/github/workspace/spk/postgresql/work-armv7-7.1/proj-8.2.1/build/lib:  lib/libproj.so.22.2.1 && :
lib/libproj.so.22.2.1: undefined reference to `curl_easy_perform'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_getinfo'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_init'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_cleanup'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_setopt'
collect2: error: ld returned 1 exit status
[221/230] Linking CXX executable bin/proj
FAILED: bin/proj 
: && /github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++ -I/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/include -D__ARM_PCS_VFP=1 -fPIC -O3 -DNDEBUG -L/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/lib -L/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/lib -Wl,--rpath-link,/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/lib -Wl,--rpath,/var/packages/postgresql/target/lib -D__ARM_PCS_VFP=1 src/CMakeFiles/binproj.dir/apps/proj.cpp.o src/CMakeFiles/binproj.dir/apps/emess.cpp.o src/CMakeFiles/binproj.dir/apps/utils.cpp.o -o bin/proj -L/github/workspace/spk/postgresql/work-armv7-7.1/proj-8.2.1/build/lib -Wl,-rpath,/github/workspace/spk/postgresql/work-armv7-7.1/proj-8.2.1/build/lib:  lib/libproj.so.22.2.1 && :
lib/libproj.so.22.2.1: undefined reference to `curl_easy_perform'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_getinfo'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_init'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_cleanup'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_setopt'
collect2: error: ld returned 1 exit status
[222/230] Linking CXX executable bin/cct
FAILED: bin/cct 
: && /github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++ -I/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/include -D__ARM_PCS_VFP=1 -fPIC -O3 -DNDEBUG -L/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/lib -L/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/lib -Wl,--rpath-link,/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/lib -Wl,--rpath,/var/packages/postgresql/target/lib -D__ARM_PCS_VFP=1 src/CMakeFiles/cct.dir/apps/cct.cpp.o src/CMakeFiles/cct.dir/apps/proj_strtod.cpp.o -o bin/cct -L/github/workspace/spk/postgresql/work-armv7-7.1/proj-8.2.1/build/lib -Wl,-rpath,/github/workspace/spk/postgresql/work-armv7-7.1/proj-8.2.1/build/lib:  lib/libproj.so.22.2.1 && :
lib/libproj.so.22.2.1: undefined reference to `curl_easy_perform'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_getinfo'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_init'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_cleanup'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_setopt'
collect2: error: ld returned 1 exit status
[223/230] Linking CXX executable bin/geod
FAILED: bin/geod 
: && /github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++ -I/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/include -D__ARM_PCS_VFP=1 -fPIC -O3 -DNDEBUG -L/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/lib -L/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/lib -Wl,--rpath-link,/github/workspace/spk/postgresql/work-armv7-7.1/install/var/packages/postgresql/target/lib -Wl,--rpath,/var/packages/postgresql/target/lib -D__ARM_PCS_VFP=1 src/CMakeFiles/geod.dir/apps/geod.cpp.o src/CMakeFiles/geod.dir/apps/geod_set.cpp.o src/CMakeFiles/geod.dir/apps/geod_interface.cpp.o src/CMakeFiles/geod.dir/apps/emess.cpp.o -o bin/geod -L/github/workspace/spk/postgresql/work-armv7-7.1/proj-8.2.1/build/lib -Wl,-rpath,/github/workspace/spk/postgresql/work-armv7-7.1/proj-8.2.1/build/lib:  lib/libproj.so.22.2.1 && :
lib/libproj.so.22.2.1: undefined reference to `curl_easy_perform'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_getinfo'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_init'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_cleanup'
lib/libproj.so.22.2.1: undefined reference to `curl_easy_setopt'
collect2: error: ld returned 1 exit status
```


build logs on the master of my fork:
https://github.com/hgy59/spksrc/actions/runs/33171311256
The builds with DSM 7.1 toolchain failed (except comcerto2k)

**Comment by th0ma7** [comment]
My claude session is still remotely accessible :).  Adding the following to libproj makefile might do the trick:
```
CONFIGURE_ARGS += -DCURL_NO_CURL_CMAKE=ON
```
