### ISSUE TITLE
dig from SynoCli Network Tools 2.4-18 does not work on Marvell38x (DS216j)

### ISSUE THREAD

**Issue by toaster** [SynoCommunity/spksrc#6287]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

synocli-net

### Package Version

2.4-18

### Device Model

DS216j

### Device Architecture

ARMv7

### Firmware Version

DSM 7.2.1-69057 Update 5

### What happened?

Trying to run `dig` (or `mdig`) fails like this:
```shell
# dig
os.c:84: fatal error: RUNTIME_CHECK((size_t)s == (size_t)64) failed
Aborted (core dumped)
```

Other commands work well (tested and `tmux`, `links`)

The 2.13 version still works:
```shell
# dig

; <<>> DiG 9.16.28 <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20560
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 27

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 9e5b42a6edea1b7a010000006710a0eeee787c2130e5ce67 (good)
;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			2703	IN	NS	k.root-servers.net.
…
```

### Reproduction steps

1. Update to 2.4-18
2. Try to run `dig`

### Install Log

```log
There is no `var` in `/var/packages/synocli-net/target/`.
```

**Comment by hgy59** [comment]
Sorry, I had this issue with cross/bind and added a patch (001-disable-l1-cache-runtime-check.patch)
And it worked in my final tests on armada370-7.1 (armv7), aarch64-6.2.4 and x64-7.1.

Are you sure you have version 2.4-19?

Ok I see, you have version 2.4-18, it is fixed in 2.4-19 of #6269

**Comment by hgy59** [comment]
it is now published (takes up to 48h until update is visible in Package Center)

**Comment by hgy59** [comment]
BTW all bind tools were affected (arpaname, delv, dig, mdig)

**Comment by toaster** [comment]
Thank you very much. 2.4-19 works fine!
