### PR TITLE
WIP Update Chromaprint to 1.4.2 and ffmpeg to 3.3.3 and dependencies

### PR DESCRIPTION
**Pull request by ymartin59**
Depends on ffmpeg package instead of Chromaprint specific cross/ffmpeg-2.2.1
Replaces openssl by gnutls because of rtmpdump
Dependencies updates:
- expat 2.2.2
- fdk-acc 0.1.5
- ffmpeg 3.3.3
- fontconfig 2.12.4
- freetype 2.8
- gmp 6.1.2
- gnutls 3.5.9
- libbluray 1.0.1
- libpng 1.6.30
- libtasn1 4.12
- libunistring 0.9.7
- openssl 1.1.0f
- opus 1.2.1
- x264 20170730-2245-stable
- x265 2.1 for PPC and 2.5 for others

_Motivation:_ Security update https://nvd.nist.gov/vuln/detail/CVE-2017-9993
_Linked issues:_ #2812 #2775 #2834

### Checklist
- [in progress] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

Do not merge yet... tests in progress...

### CODE REVIEW

**Comment by ymartin59** [comment]
Because of x265 not longer compiles on PPC since 2.2 with following errors
```
common/ppc/pixel_altivec.cpp:1: error: bad value (power8) for -mcpu= switch
common/ppc/pixel_altivec.cpp:1: error: AltiVec and E500 instructions cannot coexist
```

Fixes are pending: https://bitbucket.org/multicoreware/x265/issues?q=altivec
Until then, ffmpeg for PPC depends on a version-specific copy `cross/x265-2.1`

**Comment by ymartin59** [comment]
Wrong path, so I gave up:

- Chromaprint 1.4.x requires C++11 which is not available for arch-qoriq-5.2 (strange it is with other DSM 5.2 toolchains !). So I propose to only upgrade targeting DSM 6.x

- openssl 1.1.0f is not yet supported in rtmpdump but openssl 1.0.2 is still supported, so no need for a switch to gnutls

- I keep my work on all these libraries in a branch which may be useful for DSM 6.x

**Comment by m4tt075** [comment]
@ymartin59: Thanks for your work on this and please don't give up. You have made progress. I have cherry-picked your commit this morning and have been able to replace the proprietary ffmpeg version for TVH with yours. The only issue I stumbled over was that the PLIST file in your openssl 1.1.0f package was outdated (now obsolete). Otherwise, everything compiled fine for evansport with 6.1 toolchains. Therefore, could you separate out your work on ffmpeg and it's depends into another PR, please? This looks very promising. I will be happy to do some testing for you, if that is helpful...

**Comment by ymartin59** [comment]
@m4tt075 of course I have not given completely - see #2865
