### PR TITLE
[WIP] Prepare Update TVHeadend to 4.2

### PR DESCRIPTION
**Pull request by m4tt075**
## Motivation
TVHeadend 4.2 has not been released yet, but should be close to final. This PR compiles the master branch 4.1.x. Since TVH 4.2. is still being developed, master is a moving target. As such this PR can brake at any time. It cannot and is not supposed to be merged at this stage. It will be updated once TVH 4.2 is final. 

## Checklist
- [x] Build rule `all-supported` completed successfully with 5.2. toolchains on March 20th, 2017
- [ ] Remove `ffmpeg-3.2.4` cross-package and link to available `ffmpeg` cross-package once #2620 is merged
- [ ] Update from master to release once TVH 4.2 is final
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by m4tt075** [comment]
@Dr-Bean, @cytec: I have created this PR because the update to master requires some more substantial changes to the 4.0.9 package. Once I updated to the TVH-master source, the compilation of the statically linked ffmpeg broke. Similarly to the strategy for libhdhomerun in the 4.0.9 update, I disabled the static and enabled dynamic linking of ffmpeg. Compiling against the existing ffmpeg cross package failed because libavresample is not compiled and I have not been able to adapt the existing ffmpeg cross-package to compile it. I found workarounds on jdierkse's old github tvheadend-testing branch again (thank you!), created several new cross-packages and eventually made it compile on evansport-5.2. 

I would appreciate if you could take a look at this PR to see whether it is running in the right direction or requires structural changes (e.g. w.r.t. to the ffmpeg cross package), so that I could frontload working on fixes prior to 4.2. release. However, I understand if you don't want to spend time on this before 4.2. is actually released. If so, please just let me know and I will close this PR and re-open it once 4.2. is final.

**Comment by cytec** [comment]
just adding `--enable-avresample` didn't work? afaik we switched from static to dynamic linking with ffmpeg 3.x so that should work i guess and i'd prefer it since we already have 2 cross packages for ffmpeg

**Comment by m4tt075** [comment]
@cytec: That is what I tried first and no, it did not work. I have added all the configuration arguments that you will see in the ffmpeg-3.2 cross-package Makefile to the ffmpeg cross-package Makefile (unless they were already there of course) and it still did not work. Everything compiled except avresample. Avresample is required to compile tvheadend-master though. I don't know why the existing ffmpeg cross-package does not build avresample. Either something is broken in that package or there are configuration arguments which are incompatible with building avresample. Could not figure it out. If you have an idea, please just let me know and I will try again.

**Comment by m4tt075** [comment]
@cytec: Just figured out that libavresample can be compiled by enabling the corresponding configuration argument with @Pilou44's updated ffmpeg package (3.2.2).   😄 
I will switch the cross-package as soon as the pending PR has been merged. Thanks for looking into this, actually. Anthing else you see or I should look out for?

**Comment by cytec** [comment]
Just 2-3 things popped my eye when scrolling through the code:

1. `SPK_REV` should always increment by 1 never go down or even back to 1 (this is mostly internal stuff and do make sure DSM handles it as an update anyway)
2. `--enable-static --enable-shared` seems like it should only be either not both (might drop one)
3. `SPK_VERS` should hold the upstream version, idk how tvheadend handles that but for other packages where we use `master` from git we use the build time as version. I assume that'll be changed anyway one 4.1 is out, so that might as well can be ignored for now

**Comment by m4tt075** [comment]
Thanks, @cytec. Fixed 1. and 2. (see commits). You are right w.r.t. 3. Will be changed once 4.2. is out. I have also updated the checklist in the PR message to reflect the ffmpeg changes you proposed. I will squash all commits once 4.2. is done. 

I will keep compiling this version (master) from time-to-time to see whether the package stays intact. If anybody else is testing this and runs into issues, please let me know.

**Comment by m4tt075** [comment]
FFmpeg cross-package bumped to sync with master.

**Comment by m4tt075** [comment]
Removed deprecated faac dependency in ffmpeg-3.2.4 cross-package. Fixes compilation of 88f6281-5.2.

**Comment by m4tt075** [comment]
I have compiled all supported architectures with 5.2. toolchains in the last couple of days. Everything working except ppc853x and qoriq. They both fail here:
> make[5]: Entering directory '/home/m4tt075/builds/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-master'
WEBUI debug finished
make[5]: Leaving directory '/home/m4tt075/builds/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-master'
make[4]: Leaving directory '/home/m4tt075/builds/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-master'
CC              src/version.o
CC              src/uuid.o
CC              src/main.o
CC              src/tvhlog.o
CC              src/idnode.o
CC              src/prop.o
CC              src/utils.o
CC              src/wrappers.o
CC              src/access.o
CC              src/tcp.o
src/tcp.c: In function 'socket_set_dscp':
src/tcp.c:61: error: 'IPTOS_DSCP_MASK' undeclared (first use in this function)
src/tcp.c:61: error: (Each undeclared identifier is reported only once
src/tcp.c:61: error: for each function it appears in.)
Makefile:627: recipe for target '/home/m4tt075/builds/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-master/build.linux/src/tcp.o' failed
make[3]: *** [/home/m4tt075/builds/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-master/build.linux/src/tcp.o] Error 1

Have not been able to fix this. Can anybody help / advise?

**Comment by m4tt075** [comment]
@cytec, @ymartin59: Please see above. Any idea why this pops up for ppc architectures and what I can do about it?

**Comment by cytec** [comment]
@m4tt075 seems to be an problem with their tcp implementation, might open a ticket upstream

**Comment by m4tt075** [comment]
Thanks @cytec. I opened a ticket and @perexg kindly helped finding fixes. I have updated this PR with the required platform-dependent patches. Analogoues PRs are pending upstream. Whatever is merged upstream will be removed here. Either way, for the time being 'all-supported' builds with 5.2 toolchains.

**Comment by m4tt075** [comment]
Added libdvben50221 support as default in line with recent changes in TVH master

**Comment by m4tt075** [comment]
Some PPC compilation patches could be removed as @perexg kindly fixed upstream. Squashed some commits to make it readable again.

**Comment by m4tt075** [comment]
Adapting to upstream fixes, some cosmetics like added licenses, rebased.

**Comment by m4tt075** [comment]
Tvheadend 4.2.1 has been released today. I'm closing this PR in favor of #2749. Thanks to everybody contributing!
