### ISSUE TITLE
META: DSM 7.2 issues

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#6614]
known issues with DSM 7.2 toolchains

Collection of issues found when building packages for DSM 7.2

### kiwix
all archs fail with:
```
$ make arch-armv7-7.2 -C ./spk/kiwix
/github/workspace/spk/kiwix/work-armv7-7.2/Mustache-4.1/catch.hpp:6594:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 6594 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
      |                                             ^~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by dot-mike** [comment]
libfuse won't compile on 7.2 without a patch. Attached is a working fuse patch. Drop in `/spksrc/cross/fuse/patches/`

[003-closefrom-glibc.patch](https://github.com/user-attachments/files/21538915/003-closefrom-glibc.patch)

For example borgbackup : 
```
$ make arch-denverton-7.2 -C ./spk/borgbackup/

===>  Compiling for fuse
make[4]: Entering directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9'
Making all in include
make[5]: Entering directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/include'
make  all-am
make[6]: Entering directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/include'
make[6]: Leaving directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/include'
make[5]: Leaving directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/include'
Making all in lib
make[5]: Entering directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/lib'
  CC       fuse.lo
  CC       fuse_kern_chan.lo
  CC       fuse_loop.lo
  CC       fuse_loop_mt.lo
  CC       fuse_lowlevel.lo
  CC       fuse_mt.lo
  CC       fuse_opt.lo
  CC       fuse_session.lo
  CC       fuse_signals.lo
  CC       buffer.lo
  CC       cuse_lowlevel.lo
  CC       helper.lo
  CC       mount.lo
  CC       mount_util.lo
  CC       ulockmgr.lo
  CC       modules/subdir.lo
  CC       modules/iconv.lo
  CCLD     libulockmgr.la
  CCLD     libfuse.la
make[5]: Leaving directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/lib'
Making all in util
make[5]: Entering directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/util'
make  all-am
make[6]: Entering directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/util'
  CC       fusermount-mount_util.o
  CC       fusermount-fusermount.o
  CC       ulockmgr_server-ulockmgr_server.o
  CC       mount.fuse.o
ulockmgr_server.c:127:12: error: conflicting types for ‘closefrom’; have ‘int(int)’
  127 | static int closefrom(int minfd)
      |            ^~~~~~~~~
In file included from ulockmgr_server.c:14:
/spksrc/toolchain/syno-denverton-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/unistd.h:363:13: note: previous declaration of ‘closefrom’ with type ‘void(int)’
  363 | extern void closefrom (int __lowfd) __THROW;
      |             ^~~~~~~~~
make[6]: *** [Makefile:511: ulockmgr_server-ulockmgr_server.o] Error 1
make[6]: *** Waiting for unfinished jobs....
make[6]: Leaving directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/util'
make[5]: *** [Makefile:340: all] Error 2
make[5]: Leaving directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9/util'
make[4]: *** [Makefile:454: all-recursive] Error 1
make[4]: Leaving directory '/spksrc/spk/borgbackup/work-denverton-7.2/libfuse-fuse-2.9.9'
make[3]: *** [../../mk/spksrc.compile.mk:44: compile_target] Error 2
make[3]: Leaving directory '/spksrc/cross/fuse'
make[2]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[2]: Leaving directory '/spksrc/spk/borgbackup'
make[1]: *** [../../mk/spksrc.supported.mk:74: build-arch-denverton-7.2] Error 1
make[1]: Leaving directory '/spksrc/spk/borgbackup'
```

**Comment by hgy59** [comment]
In #6717 the build of cross/cpulimit was fixed for DSM 7.2 and SRM 1.3

DSM 7.2 and SRM 1.3 toolchains are lacking the header files `sys/sysctl.h` and `bits/sysctl.h`

**Comment by hgy59** [comment]
`cross/tcp_wrappers` fails to build for DSM 7.2 and SRM 1.3

several warnings and finally
```
percent_m.c:32:25: error: ‘sys_nerr’ undeclared (first use in this function)
```

The following packages depend on tcp_wrappers
- sslh
- stunnel
