### PR TITLE
Make Python3 build again; bump to 3.5.5

### PR DESCRIPTION
**Pull request by chickenandpork**
_Motivation:_ I'm a fan of Home Assistant which needs 3.5.3 or later, and it's a real dependency, not just a "we don't know whether it'll work with 3.5.2".

The intention is to move through to 3.7.0 once this lands so that the logic here and the logic to move to 3.7.0 are separate.  The upgrade to 3.7.0 should be fairly straightforward after this diff.

_Linked issues:_ Scratching my own itch, I've seen this mentioned in chats.  I saw #3379 filed a few days ago by @ymartin59 

### Checklist
- [] Build rule `all-supported` completed successfully
    - openssl does not seem to support all ARM:
        arm_arch.h:46:6: error: #error "unsupported ARM architecture"
    - (cd spk/python3 && make all-supported) ongoing (keep running out of space)
- [x] Package upgrade completed successfully. (my tests have typically been upgrades)
- [x] New installation of package completed successfully. (both cmdline and by web UI) -- note that some users may be confused that this updates python3, not python nor py3k, so there may be three similar icons in the "installed" list.

I've been granted permission by my employer to contribute to spksrc without risk of IP confusion.  I am required to explicitly write that my contribution to this project is solely in my personal capacity, and I am not conveying any rights to any intellectual property of any third parties.  I'm not a fan of boiler-plate, but I'm glad I'm able to finally release this work.

The test case I'm using to validate a clean, good install -- before going forward with a home assistant install -- is the following code:

```
import time
import sqlite3
from lxml import etree
from ctypes import c_bool
from threading import Thread

def myfunc(i):
    print ("sleeping 5 sec from thread %d" % i)
    time.sleep(5)
    print ("finished sleeping from thread %d" % i)

for i in range(10):
    t = Thread(target=myfunc, args=(i,))
    t.start()
```

You'll notice that this includes an explicit import of `ctypes`, `lxml`, and `sqlite3`, as well as imports/exercises some `threading`.  `types` tends to show where the resulting Python cannot do wheels or CFFI, which in turn would make `lxml` fail.  `sqlite3` and threading are my initial requirements.

Output of the test code is as expected:
```
bash-4.3$ python3 ~/test.py
sleeping 5 sec from thread 0
sleeping 5 sec from thread 1
sleeping 5 sec from thread 2
sleeping 5 sec from thread 3
sleeping 5 sec from thread 4
sleeping 5 sec from thread 5
sleeping 5 sec from thread 6
sleeping 5 sec from thread 7
sleeping 5 sec from thread 8
sleeping 5 sec from thread 9
finished sleeping from thread 2
finished sleeping from thread 1
finished sleeping from thread 4
finished sleeping from thread 6
finished sleeping from thread 0
finished sleeping from thread 3
finished sleeping from thread 5
finished sleeping from thread 7
finished sleeping from thread 9
finished sleeping from thread 8
```

Note also that the `python3` binary is appended to `$PATH`, and needs to `LD_LIBRARY_PATH` nor wrapper.

### CODE REVIEW

File: cross/attr/PLIST [hunk 1]
```diff
@@ -1,7 +1,7 @@
 bin:bin/attr
 bin:bin/getfattr
 bin:bin/setfattr
-lnk:libexec/libattr.so
+lnk::libexec/libattr.so
```
Comment (m4tt075) [inline cross/attr/PLIST]: Please undo. Fine as it was.

File: spk/python3/Makefile [hunk 2]
```diff
@@ -1,7 +1,7 @@
 SPK_NAME = python3
 SPK_SHORT_VERS = 3.5
-SPK_VERS = $(SPK_SHORT_VERS).2
-SPK_REV = 6
+SPK_VERS = $(SPK_SHORT_VERS).5
+SPK_REV = 1
```
Comment (m4tt075) [inline spk/python3/Makefile]: SPK_REV needs to increment, independent of major, minor or patch versions. Please change to 7.

Comment (chickenandpork) [reply spk/python3/Makefile]: updated per both your suggestions

**Comment by ymartin59** [comment]
Thanks for contributing. Recent Python 2.7 was really painful, so I hope Python 3 will be easier.
I have to check compilation and understand what is wrong with ARM as current version is OK there.

**Comment by chickenandpork** [comment]
Sadly, the _sqlite3 module is still not usable.  Needs more work.  I’m moving house so my ability to test will disappear for a week.    I’ll need to figure out a static-analysis way to confirm that the module made it in.  Then I’ll check where providence of the dependent libs got lost before setup.py magically detects and activates the module.

Is there a “make python3-sanity” -sort of build target I can exploit?  Does anyone else do this in any other spk?

**Comment by codexown** [comment]
Can be added lxml library? is missing in this package

**Comment by chickenandpork** [comment]
FYI, new employer means new permissions to work on OSS.  Waiting on that.

**Comment by kergoth** [comment]
Just a side note that there are other projects around that do massive amounts of cross-compilation which can be useful resources. I'd check the python3 build in buildroot and the python3 recipe files in openembedded-core (openembedded/yocto projects) if you're running into any difficulties.

**Comment by chickenandpork** [comment]
I have this working.

My test is "python3 'import sqlite3; import lxml; print ("OK")'  " on my NAS (DS1515+)

Pending permission to release (ie update the branch under this PR)

**Comment by Safihre** [comment]
Yes let's show us :)

**Comment by Safihre** [comment]
Any new developments on this? @chickenandpork

**Comment by chickenandpork** [comment]
Waiting still on corporate green light.  Also had threading problem maybe now fixed.

**Comment by Safihre** [comment]
Corporate?

**Comment by chickenandpork** [comment]
@Safihre yeah, "corporate".  Suffice to say, contributing to open source without permission can lead both to arguments over IP ownership, plus risk of implicitly over-granting license or release can be a huge legal burden.  For example, I once had to clean up a linux build so that GPL requirement to provide source code was met while code the reseller thought was infringing was removed from the linux kernel code they released.  Not this employer, but similar hoops to jump through (In that case, French, Chinese, and US IP laws).

So, yeah, took a bit of waiting, but I got the green light, updated this PR, and included test output.  It dates back to ... August 1 or so... but I don't think anyone's edited the same files.

I can do an immediate version-bump now that python-3.5.6 is released, but honestly, I'd rather get this merged and safe before making any iterations on top.

**Comment by Safihre** [comment]
Could you maybe rebase on `develop`? It now wrongly includes some commits from there.
What company is this? 🐙

**Comment by chickenandpork** [comment]
@Safihre I didn't see a branch `develop` but rebased on `master` if that works.  Merge still has no conflicts but the conspicuous list of commits since my diff is eliminated now :)

I've been at a HG shop where the tools are really really optimized, I'm getting used to github again, rebasing, etc.  I'm not yet stacking diffs in git :-/

Thanks for reviewing; I might be out-of-pocket a few days until Wednesday if there is anything else, but I'd rather address anything non-critical (ie some of the efficiency patches in cross/python/patches) in a followup 3.5.6 diff that I've got almost cleaned up.

**Comment by Safihre** [comment]
Building it now for all releases: https://travis-ci.org/Safihre/spksrc/builds/425653255
Output: https://github.com/Safihre/spksrc/releases/tag/python3-build

**Comment by chickenandpork** [comment]
@Safihre what else remains to permit this PR to merge ?

**Comment by Safihre** [comment]
@chickenandpork  I could technically merge and publish but there's always the last check/verdict is always given by @ymartin59!

**Comment by chickenandpork** [comment]
rebased on HEAD (82b71c5278e3f7e81149f74a96fac990de677a7b)

**Comment by ymartin59** [comment]
OK for me. I would invite to rename Makefile targets into new naming convention like "python3_custom_compile", "python3_custom_install", "python3_post_install"... But I leave it for next upgrade PR.

**Comment by ymartin59** [comment]
I wait for borgbackup msgpack update https://github.com/SynoCommunity/spksrc/pull/3418/files#diff-f0d57d6a6d8f7395594a144838d498bd before publishing Python3 packages.

**Comment by codexown** [comment]
End

**Comment by hogi1200** [comment]
Hello @ymartin59,
how about publishing this change now without borgbackup? Python 3.5.5 works now for almost 2 months, but without an "official" delivery. I think many people from homeassistant community would appreciate.
Thanks!
